import { NavigationBar } from '@/components/nav-bar';
import './globals.css';
import { Montserrat } from 'next/font/google';
import { Footer } from '@/components/footer';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className + " flex flex-col justify-between h-screen"}>
        <div className=''>
          <NavigationBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
